### PR TITLE
Bump `snapdragon-node`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
For https://github.com/jonschlinkert/snapdragon/issues/6.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
This will be a major bump here as well.

**Comment by wtgtybhertgeghgtwtg** [comment]
Want me to close this, then?

**Comment by jonschlinkert** [comment]
No, I appreciate the pr, I can still update this I just wanted to let you know it would be a major bump because of the changes in snapdragon-util.

**Comment by doowb** [comment]
Thanks for the PR @wtgtybhertgeghgtwtg. Looks like the dependency has already been updated.

**Pull request closed without merging**
