### PR TITLE
Bump `snapdragon-util`.

### PR DESCRIPTION
**Pull request by wtgtybhertgeghgtwtg**
To `snapdragon-util@4`.  The latest is `snapdragon-util@5.0.1`, but that requires `node>=6`.
All this really does is dedupe the version of `kind-of` being used and take out the `is-buffer` transitive dependency.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Did you test this will all downstream libraries?

**Comment by wtgtybhertgeghgtwtg** [comment]
Just `braces`.  `snapdragon`, `snapdragon-cheerio`, and `breakdance` all use older versions of `snapdragon-node`.

**Comment by wtgtybhertgeghgtwtg** [comment]
This is breaking with the latest `snapdragon`.

**Comment by wtgtybhertgeghgtwtg** [comment]
Actually it doesn't, I was mistaken.  It works with https://github.com/here-be/snapdragon/pull/18, too.

**Comment by jonschlinkert** [comment]
closing since this was refactored and snapdragon-util was removed. thanks for the pr!

**Pull request closed without merging**
